package core.application.member.application.exception

import core.application.common.exception.BusinessException

class InvalidMemberManagementTeamException : BusinessException(MemberExceptionCode.INVALID_MEMBER_MANAGEMENT_TEAM)
